import queue
from dataclasses import dataclass, field
from typing import Optional, Dict, Any

@dataclass
class ConsciousnessState:
    mode: str = "awake"          # "awake", "sleep", "dream", "idle"
    last_tick_ts: float = 0.0
    last_dream_ts: float = 0.0
    current_focus: Optional[str] = None
    current_emotion: Optional[str] = None # Or a more complex structure, e.g., Dict[str, float]
    current_mood: Optional[str] = None    # Or a more complex structure
    notes: Dict[str, Any] = field(default_factory=dict) # For transient internal notes/insights

global_consciousness_state = ConsciousnessState()

# Queue for proactive questions generated by the orchestrator, to be picked up by the main response path
proactive_question_queue = queue.Queue()
